### ISSUE TITLE
Upgrade to version 120

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/chromium#38]
High-level ticket for tracking progress on upgrading to version 120.

```[tasklist]
### Tasks
- [ ] Get minigbm working on kernel 5.15
- [ ] Get Ozone-DRM working again
- [ ] Boot into full-screen Chromium
- [ ] Get keyboard working
```

**Comment by EwanRoycroft** [comment]
Got ozone demo working using FydeOS patches for minigbm and the kernel.

See: https://github.com/bbc/minigbm/tree/fydeos

**Comment by EwanRoycroft** [comment]
Chromium was failing to load with error `Check failed: delegate_ == delegate`.

This was caused by commits 9c265767886f30c1dda6239bf14b1bce90f8a164 and 27201044a01b2a463856dfb801c08395b9bbd096, and by the renaming of `--force-system-compositor-mode` to `--enable-running-as-system-compositor`.

See: https://paper.dropbox.com/doc/2023-10-24-v118-chrome-delegate-check-failed--CD0AhZixTupzS_RwTchcgFlMAg-lk3TwvWOkSeQUtIuh8oNh
